### PR TITLE
Correcting bug for SE calculation

### PR DESCRIPTION
**Pull request by coderkol95**
$$ Sampling \  error (S.E.) =  \frac{\sigma}{\sqrt{n}}$$

## `Previous scenario:`

Assume 100 observations with chunk size being 10.  The S.E. was calculated as std(all 100 data points) and not the std of sample(chunk) means.

## `What this PR addresses:`

Computes the S.E. as the std( chunk means ).

### CODE REVIEW

**Comment by nnansters** [comment]
Hey @coderkol95 , thanks for your contribution! @nikml will take a look at this ASAP! :+1:

**Comment by nikml** [comment]
Hello @coderkol95 

The calculation is working as intended. The $\sigma$ in the sampling error formula refers to the distribution we are sampling from* - not at the standard deviation of the mean calculated from those samples. This distribution from which we are sampling the chunk data is approximated by the whole reference dataset (in the ideal case where there is no drift). Hence the reconstruction errors for the whole reference are the base population from which reconstruction error samples are drawn for the chunks.


\* 
We are trying to describe that in our [glossary entry for standard error](https://nannyml.readthedocs.io/en/stable/glossary.html#term-Standard-Error) but we likely should do better.
There is also a good excerpt in the [standard error wikipedia page](https://en.wikipedia.org/wiki/Standard_error):
Screenshot 2023-03-13 at 22-35-21 Standard error - Wikipedia

I 'll close the PR but feel free to ask any further questions you may have.

**Comment by coderkol95** [comment]
> Hello @coderkol95
> 
> The calculation is working as intended. The σ in the sampling error formula refers to the distribution we are sampling from* - not at the standard deviation of the mean calculated from those samples. This distribution from which we are sampling the chunk data is approximated by the whole reference dataset (in the ideal case where there is no drift). Hence the reconstruction errors for the whole reference are the base population from which reconstruction error samples are drawn for the chunks.
> 
> * We are trying to describe that in our [glossary entry for standard error](https://nannyml.readthedocs.io/en/stable/glossary.html#term-Standard-Error) but we likely should do better. There is also a good excerpt in the [standard error wikipedia page](https://en.wikipedia.org/wiki/Standard_error): Screenshot 2023-03-13 at 22-35-21 Standard error - Wikipedia
> 
> I 'll close the PR but feel free to ask any further questions you may have.

Hi @nikml,

In most real world scenarios, this reference dataset does not(also cannot) represent the entire population. In this scenario, this σ is incorrect. It would instead be better to use the approximate formula.

**Comment by nikml** [comment]
@coderkol95 You are right that the reference dataset is imperfect approximation of the model population and depending on each use case.

The approach we currently use is also an approximate formula. The reference dataset is a sample from the population and therefore we are in practice using this formula from the [Wikipedia Standard Error page](https://en.wikipedia.org/wiki/Standard_error):
Screenshot 2023-03-14 at 11-26-34 Standard error - Wikipedia

Your proposal has the following steps:
1. It considers each reference chunk a sample
2. It calculates mean of reconstruction error for each reference chunk
3. It calculates the final reconstruction error sampling error by taking the standard deviation of the calculated reference chunk means divided by the square root of the chunk size.

The problem with this approach is that:
- The reference chunks, being subsets, of the reference dataset are even less representative of the population and therefore more prone to be influenced by randomness.
- You wouldn't need to divide by root of the sample size in this case to calculate standard error correctly. Meaning [this line in the PR would need to be changed](https://github.com/NannyML/nannyml/pull/249/files#diff-30ac0ebc435b842594cf94ee4f172fea4464624926f76b0fbf099f1a0601a6b9R358)
Remember standard error is the standard deviation of the calculated statistic. You get many estimates of the statistic, mean is this case, at step 2. Therefore you only need to calculate the standard deviation at step 3.

But even accounting for this fix in your PR I 'd be cautious of using that approach because in practice chunk sizes can vary with each chunk and small chunks are more prone to outsized impact of randomness.

**Comment by coderkol95** [comment]
> 

Thanks for the detailed reply @nikml

**Pull request closed without merging**
