### PR TITLE
Modified the code to include the new argument 'problem_type'

### PR DESCRIPTION
**Pull request by NeoKish**
The images also needs to be changed but since the doc/examples section is in WIP, I haven't included the modified ones in this PR.

### CODE REVIEW

**Comment by nnansters** [comment]
Hey @NeoKish , fair point, as always.

This example seems a bit out of date, I'll need to walk through this one again to check if all of the sections are still required. 

Apart from that we still have to update the docs sources so they use the code snippets from our notebooks instead. That's somewhat bigger then the current fix. I can do that on Monday. OK if I update this PR with those changes?

Thanks for reporting!

**Comment by NeoKish** [comment]
@nnansters, yeah and I think it would be better to close this PR as the code snippets are going to be used and the PR changes wouldn't be applicable.

**Comment by nnansters** [comment]
Did the updates, feel free to have a look!

**Comment by NeoKish** [comment]
@nnansters, Great and thanks for including me in the PR.  I have noticed that the user warning for underpopulated chunk doesn't seem to be popping up. Has that been deprecated?

**Pull request merged**
