### PR TITLE
created the ReaderException

### PR DESCRIPTION
**Pull request by baskervilski**
Addressing #109 

Tox ran, all envs passing.

### CODE REVIEW

**Comment by baskervilski** [comment]
The pyproject.toml modification was to fix a parsing error which was popping up at tox env setup. See failed action: https://github.com/NannyML/nannyml/actions/runs/2989600353

**Comment by nnansters** [comment]
Yeah, was looking to find where that syntax crept in. Odd.

**Comment by nnansters** [comment]
That syntax did not break things before, very odd. I'll have a look at any changes in Poetry versions. 

Thank you very much for reporting and contributing! Don't hesitate to call me out on other things I've missed :-)

**Comment by baskervilski** [comment]
@nnansters , the parsing was crashing already in my local env, but I thought I messed something up during the setup, so I didn't commit that change at 1st, but then I saw it happening in Actions here also.

**Pull request merged**
