### PR TITLE
Use np.histogram_bin_edges to compute bin edges for ECE

### PR DESCRIPTION
**Pull request by Jebq**
# What is this PR for ?

This PR is intended at improving the binning used in the calibration step by using `np.histogram_bin_edges` instead of the current `_get_bin_index_edges` function.

It also adds a new `calibration_bin_count` parameter to `CBPE` to be able to tune the number of bins to use in `needs_calibration` function.

Please note that the default values for `bin_count` are still `10`. However it would probably better to switch to `auto` or `fd` as it would be generally better.

# How was it tested?

New tests added in `tests/test_calibration.py` to validate the new behaviour.
`poetry run tox` is passing.

### CODE REVIEW

**Review by nnansters — COMMENTED** [review]
Looks great @Jebq , definitely an improvement. 

@jakubnml  : what do you think concerning the remark on default binning behavior?

**Comment by jakubnml** [comment]
Hi @Jebq, that's indeed a great PR. Two things from my side:

1. Reconsider the parameter`'right'` that you use in `np.digitialize`, I ran this binning with some randomly generated data and it results in a very small first bin very often. See the example here:

```
x = np.linspace(0,1,100)
bin_edges = np.histogram_bin_edges(x)
bin_edges[-1] += 1e-8

bins_proba = np.digitize(x, bin_edges, 'right')
np.unique(bins_proba, return_counts=True)
```
outputs:

```
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64),
 array([ 1,  9, 10, 10, 10, 10, 10, 10, 10, 10, 10], dtype=int64))
```

while without this option:

```
bins_proba = np.digitize(x, bin_edges)
np.unique(bins_proba, return_counts=True)
```

gives more reasonable:

```
(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64),
 array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10], dtype=int64))
```

2. The proposed change significantly changes our default behavior. Currently we get 10 bins of **equal size**, the changes introduced will give us 10 bins of **equal width**. Both methods have their pros and cons. Equal sized bins reduce the risk that we will get bins with a very few observations, this is partially mitigated by the fact that we weight by the size of the bing. Equal-width bins help us to compare more relevant data though. For now we have tested only the equal-sized approach. We know that it is good enough. Your comment is right though - other methods may be better and your code allows to use other methods as well. 

Anyways, having another look on calibration is on our road map and we want to research it thoroughly (in about 2 or 3 months). For now I'm hesitant to change the default behavior, but I also want this work that you did to become a part of the library as we will have to do it at some point anyways. Can we merge both worlds @nnansters and just have two methods for calibration checks?

**Comment by jakubnml** [comment]
Update on the topic:

I have recently realized that our approach has one strong disadvantage: it can put the same predicted probabilities into different bins and this is not right. Imagine such data:

```
y_pred_proba = [0.2, 0.2, 0.2, 0.5, 0.6, 0.9]
y_true      =  [  0,   1,   0,   0,   1,   1]
```

If we split into 3 **equal-size** bins we would get:

```
y_pred_proba = [0.2, 0.2,   0.2, 0.5,   0.6, 0.9]
y_true      =  [  0,   1,     0,   0,     1,   1]
```

so the 0.2 get separated. There's unwanted random stuff going on as well, cause the following is just as likely (notice the y_true change):

```
y_pred_proba = [0.2, 0.2,   0.2, 0.5,   0.6, 0.9]
y_true      =  [  0,   0,     1,  0,     1,   1]
```

And the ECE would might end up being different. We should therefore switch to almost-equal-sized binning with no bin splitting on the same value.

**Comment by Jebq** [comment]
Hi @jakubnml, and sorry for the late reply.
Thank you for your feedback. I agree with all the points you raised, especially that the issue with having few observations within a bin is inflated by using the equal-width binning approach.

**Pull request closed without merging**
